### ISSUE TITLE
switch from config file to env variables

### ISSUE THREAD

**Issue by axe312ger** [contentful-userland/gatsby-contentful-starter#15]
This will make it easier to deploy to netlify and similar services as we can just provide env variables for the credentials instead of creating/committing the `.contentful.json` file

**Comment by brampling** [comment]
Is this related to https://github.com/contentful-userland/gatsby-contentful-starter/pull/14 or did we have the same thought simultaneously?

**Comment by axe312ger** [comment]
same thought actually :)

go #14 @stefanjudis

**Comment by Pustur** [comment]
Seems like #18 has been merged, maybe you can close this issue?
