### ISSUE TITLE
add cleanup script

### ISSUE THREAD

**Issue by axe312ger** [contentful-userland/gatsby-contentful-starter#16]
Easy setup after install and config is very useful but clutters the repo. How about adding a cleanup script?

We could cleanup dependencies  `npm uninstall contentful-import inquirer`
https://github.com/contentful-userland/gatsby-contentful-starter/blob/master/package.json#L9-L26

Clean up the folder structure:
`rm bin contentful`

And remove two npm scripts:
https://github.com/contentful-userland/gatsby-contentful-starter/blob/master/package.json#L46-L47

**Comment by stefanjudis** [comment]
Great idea. The user should then commit afterwards or do you have sth better in mind?
