### ISSUE TITLE
Make the starter completely responsive

### ISSUE THREAD

**Issue by stefanjudis** [contentful-userland/gatsby-contentful-starter#2]
The current version does not work very well on mobile. That should be improved. :)

**Comment by mattbag** [comment]
I'll see if I can have time next weekend! What methodology for css did you guys pick? I guess anyway css grid with flex fallback for the layout? 
Any constrictions about the design? Not that I'm a good designer but I can check dribble and dunk something... Good job so far!

**Comment by stefanjudis** [comment]
That's great Matt. 🎉

> I'll see if I can have time next weekend! What methodology for css did you guys pick? I guess anyway css grid with flex fallback for the layout?

No methodology so far... I'm personally up for anything as long as it's consistent and not too much overhead. Right now it's hand written.

> Any constrictions about the design? Not that I'm a good designer but I can check dribble and dunk something... Good job so far!

You've got free hand and we can give each other feedback about it? :)
Personally I think the looks of the current implementation are "relatively pretty". :D

**Comment by axe312ger** [comment]
Fixed in #25
