### ISSUE TITLE
User ID not matching in graphql query

### ISSUE THREAD

**Issue by MadeByMike** [contentful-userland/gatsby-contentful-starter#23]
I was migrating the gatsby-contentful-starter to version 2 and had an issue where the query for `allContentfulPerson` was returning null. At first, I thought the created Id was wrong, but more testing proved the query was failing. Interestingly it worked for the name and other fields, but not id. Here is a gif:

![query](https://user-images.githubusercontent.com/1320567/43040665-001cb8e4-8d8d-11e8-8d7a-9b1e1b8b465f.gif)

I did update dependencies in the process of migrating to v2. Here is a repo if you'd like to compare or clone and see if you can replicate: https://github.com/MadeByMike/gatsby-contentful-v2

**Comment by stefanjudis** [comment]
Hey Mike, you're right. :)

It turns out there is a type in the query a leading `c` which seems to work fine in Gatsby V1 but rightfully doesn't work in V2. I'll adjusted the ID and that should be fine then. :)

Could you check if deleting the `c` does fix things on your end, too?

**Comment by stefanjudis** [comment]
Turns out the `c` is part of g v1 and looks like it has to be removed for v2. 🤦🏻‍♂️

**Comment by MadeByMike** [comment]
Hmmmm, Not for me I do get a different error though:

![image](https://user-images.githubusercontent.com/1320567/43355591-54af6b76-92a2-11e8-92ef-59b1d0b38456.png)

I don't understand what this query has to do with Gatsby? I thought these filter functions were part of `cfgraphql` or `gatsby-source-contentful`?

**Comment by MadeByMike** [comment]
Ok My bad! There is a mismatch between my version of Gatsby and my version of `gatsby-source-contentful` and yes gotta remove the `c` -- This is come-up again 😆

**Comment by axe312ger** [comment]
Ahh here we go. As far as I remember this changed/was added some time ago in gatsby v1.

Well with v2 everything is sorted out, I guess :)
