### ISSUE TITLE
hot reloading doesn't work

### ISSUE THREAD

**Issue by designforhuman** [contentful-userland/gatsby-contentful-starter#32]

**Comment by stefanjudis** [comment]
Hello @designforhuman,

For me, hot-reloading is working. Can you please provide more information. :)


![hot-reloading-bug](https://user-images.githubusercontent.com/962099/44398264-94a47d80-a543-11e8-965b-5cb30babb193.gif)


I'm happy to help and reopen this issue then.

**Comment by ile** [comment]
Maybe @designforhuman meant that reloading changed data from Contentful doesn't work? 

It doesn't work for me. I'm not sure if it should? Should it?
