### ISSUE TITLE
Starter kit and contentful UI list different tokens

### ISSUE THREAD

**Issue by kevzettler** [contentful-userland/gatsby-contentful-starter#42]
the `yarn setup` starter kit asks for :

```
? Your Space ID
? Your Content Management API access token
? Your Content Delivery API access token
```
The contentful UI at Settings -> API Keys lists:
```
Space ID
Content Delivery API - access token
Content Preview API - access token
```

i've tried various permutations and getting `403` when trying to complete `yarn setup`

**Comment by kevzettler** [comment]
To add confusion it appears that `.contentful.json` only uses 2 values.  `spaceId` and `accessToken`

**Comment by stefanjudis** [comment]
Heyo. 👋🏻

The management token is to import data and has to be a write token. You find it in the Contentful UI in the API keys section under "Content Management Tokens". This token will only be used during `setup`. You should not commit this token anywhere as it has the same access rights as the logged in user.

The preview and delivery tokens are read only tokens and can then be used to fetch data (and it's no biggie to have them in a public config file). These will be used after the setup is completed.

<img width="563" alt="screenshot 2019-01-28 11 04 40" src="https://user-images.githubusercontent.com/962099/51828764-334bbc00-22e4-11e9-84d7-509e9f6f7919.png">

Hope that helps. :)

**Comment by kevzettler** [comment]
thanks @stefanjudis missed the tabs in the UI
