### ISSUE TITLE
Use contentful-export to create export file dynamically

### ISSUE THREAD

**Issue by hennessyevan** [contentful-userland/gatsby-contentful-starter#50]
I think the `setup script` is great it does great to get things started. However, while the user already has to provide their space and tokens for the script should we not also have an export script as a convenience that would use [contentful-export](https://github.com/contentful/contentful-export) to generate the necessary export json?

Let me know if you'd like a PR for this.

**Comment by stefanjudis** [comment]
@hennessyevan Thanks for the idea and sorry that this was not answered when you opened the issue.

The purpose of this starter is to get people going quickly. I'm not sure if we'd need export functionality. Happy to discuss this further, but I'll close for now. :) 

(I'm cleaning up issues 🙈)
