### ISSUE TITLE
Error when trying to add a post

### ISSUE THREAD

**Issue by ayohewitt** [contentful-userland/gatsby-contentful-starter#53]
I can duplicate the starter posts and change the contents of those post and everything works fine. However, when I try and add a new post. I keep getting an error.
![Screen Shot 2019-07-15 at 12 35 44 AM](https://user-images.githubusercontent.com/49599658/61195866-f5c3cb00-a698-11e9-9b3e-225e5c5f8f03.png)

**Comment by ocundale** [comment]
This error is down to the fact that it is trying to add tags for blog posts which have no tags.
The code should check for this to prevent errors, I have added a fix, which needs reviewing before merge.

**Comment by jpalmieri** [comment]
Addressed in #59
