### ISSUE TITLE
Update gatsby-config.js to match the .env.example

### ISSUE THREAD

**Issue by thecodingwhale** [contentful-userland/gatsby-contentful-starter#70]
The `.env.example` have expect ENV variables like this:
```
CONTENTFUL_SPACE_ID=''
CONTENTFUL_ACCESS_TOKEN=''
```

But in `gatsby-config.js` in line 8 it required  `CONTENTFUL_HOST`
```
const contentfulConfig = {
  spaceId: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  host: process.env.CONTENTFUL_HOST,
}
```

To match the expectation please do delete the line 8.

**Comment by stefanjudis** [comment]
Thanks for filing this issue. The `host` property is used for using [the preview api](https://www.contentful.com/developers/docs/references/content-preview-api/#/reference/spaces/space/get-a-space/console/js). I added a comment to make that more clear. 

Hope that helps. :)

**Comment by thecodingwhale** [comment]
thank you @stefanjudis :)
