### ISSUE TITLE
yarn install failed

### ISSUE THREAD

**Issue by makwanahardik** [contentful-userland/gatsby-contentful-starter#82]
node : v14.3.0
yarn : 1.22.4
Gatsby CLI version : 2.12.55

![Screenshot 2020-08-06 at 4 39 23 PM](https://user-images.githubusercontent.com/32458204/89525210-78b74680-d803-11ea-9b8d-1faa5235a9a7.png)

**Comment by stefanjudis** [comment]
@makwanahardik Thanks for reporting this. :) Npm is [struggling right now](https://status.npmjs.org/). Could you check again when this is resolved? :)

**Comment by makwanahardik** [comment]
@stefanjudis  now `yarn install` works.

**Comment by stefanjudis** [comment]
Great! Closing then
