### ISSUE TITLE
Error: Please make sure the destination space have the same default locale as the source

### ISSUE THREAD

**Issue by mccrodp** [contentful-userland/gatsby-contentful-starter#9]
Hey, just checking this out with an existing Contentful instance of default locale `en`:

````
 ✖ Checking if destination space already has any content and retrieving it
   →       Default locale for destination space: en
   Apply transformations to source data
   Push content to destination space


The following 1 errors and 0 warnings occurred:

16:42:59 - Error: Please make sure the destination space have the same default locale as the source Default locale for source space : en-US Default locale for destination space: en

Stored the detailed error log file at:
/Users/paulmccrodden/dev/contentful-starter/contentful-import-error-log-aiu1iuazs7do-2018-02-25T16-42-82.json
{ ContentfulMultiError: Errors occured
    at /Users/paulmccrodden/dev/contentful-starter/node_modules/contentful-import/dist/index.js:195:26
    at <anonymous>
  name: 'ContentfulMultiError',
  errors:
   [ { ts: '2018-02-25T07:42:31.592Z',
       level: 'error',
       error: [Object] } ] }
````

Not sure where it is referring to, where do I have to change on code side to to allow `en` locale? Thanks.

**Comment by stefanjudis** [comment]
So you wanted to import data into a space that already has data?
(I'd recommend to go with a new space)

The locales configuration is here. 👇🏻
https://github.com/contentful-userland/gatsby-contentful-starter/blob/master/contentful/export.json#L1063

I'm not completely sure but I don't think we have the locale `en`. Usually it's `en-US` or `en-GB`. Is this maybe what you're running into?

**Comment by mccrodp** [comment]
Ahhh, it imports data, I didn't know that. Ok, so it's better starting with a blank Space on Contenful side.

Actually you do have `en` Contentful side (I changed my Space to use it) and thankfully so, as most simple i18n sites use English and one other language, it doesn't matter so much on the sub locale unless you're working on something of larger magnitude.

I'll check this out again when I have time with a new Space and see what happens :)

**Comment by Khaledgarbaya** [comment]
hi @mccrodp, when creating the space make sure it has the same default locale as the space you exported the data from.

![screen shot 2018-02-26 at 09 26 37](https://user-images.githubusercontent.com/1156093/36660150-5f9b8db4-1ad7-11e8-91e0-e18eba9e176b.png)

**Comment by mccrodp** [comment]
Hey. Thanks. I think I'm missing something at the moment. I just followed the CLI, not sure what yo are referring to export, I didn't look to export anything, just ran the CLI. Is there something I've missed or is missing from the README? Thanks.

**Comment by Khaledgarbaya** [comment]
yeah the JSON exported is from a space with the default locale `en-US` and the space you created was `en`

**Comment by stefanjudis** [comment]
Closing here, because I assume this was resolved. 🙈 Happy to have a detailed look if needed. :)
